### ISSUE TITLE
xcode 8.2 clean checkout with git submodules checked out -  not working.

### ISSUE THREAD

**Issue by johndpope** [utahwithak/MapGen#1]
swift is so volatile. I wonder if you could take a look?
<img width="1378" alt="screen shot 2017-01-04 at 17 18 46" src="https://cloud.githubusercontent.com/assets/289994/21661345/a7c491fa-d2a1-11e6-8940-45706d6d2589.png">

**Comment by utahwithak** [comment]
should hopefully be fixed now. this code is super nasty and old though. use at your own risk!

**Comment by johndpope** [comment]
Thanks Carl
